export const navData = [
    { name: 'All', id: 1 },
    { name: 'Mixes', id: 2, },
    { name: 'Coding', id: 3 },
    { name: 'Mantras', id: 4 },
    { name: 'NextJS', id: 5 },
    { name: 'Music', id: 6 },
    { name: 'Education', id: 7 },
    { name: 'Podcast', id: 8 },
    { name: 'Live', id: 9 },
    { name: 'Gaming', id: 10 },
    { name: 'Motivation', id: 11 },
    { name: 'Sport', id: 12 },
    { name: 'Fashion', id: 13 },
    { name: 'Beauty', id: 14 },
    { name: 'Comedy', id: 15 },
    { name: 'Gym', id: 16 },
]